app {
  inputDir = "./docs"
  outputDir = "./data"
}

ollama {
  baseUrl = "http://localhost:11434"
  embeddingModel = "nomic-embed-text"
}

chunking {
  fixedSize = 1200
  overlap = 200
}

search {
  topK = 5
}

